const client = window.supabaseClient;
const courseNames = { ai: "AI수처리", visualization: "경영정보시각화", accounting: "스타트업세무전산회계", excel: "비즈니스엑셀" };
const loginView = document.querySelector("#login-view");
const adminView = document.querySelector("#admin-view");
const loginMessage = document.querySelector("#login-message");
const formMessage = document.querySelector("#form-message");
let notices = [];
async function updateView() { const { data: { session } } = await client.auth.getSession(); loginView.hidden = Boolean(session); adminView.hidden = !session; if (session) loadNotices(); }
document.querySelector("#login-form").addEventListener("submit", async (event) => { event.preventDefault(); loginMessage.textContent = ""; const { error } = await client.auth.signInWithPassword({ email: document.querySelector("#email").value, password: document.querySelector("#password").value }); if (error) { loginMessage.textContent = "로그인에 실패했습니다. 이메일과 비밀번호를 확인해 주세요."; return; } updateView(); });
document.querySelector("#logout").addEventListener("click", async () => { await client.auth.signOut(); updateView(); });
async function loadNotices() { const filter = document.querySelector("#filter-course").value; let query = client.from("notices").select("*").order("published_at", { ascending: false }); if (filter !== "all") query = query.eq("course", filter); const { data, error } = await query; if (error) { document.querySelector("#admin-notice-list").innerHTML = '<p class="message">공지사항을 불러오지 못했습니다. Supabase 설정을 확인해 주세요.</p>'; return; } notices = data; renderNotices(); }
function renderNotices() { const list = document.querySelector("#admin-notice-list"); if (!notices.length) { list.innerHTML = '<p class="message">등록한 공지사항이 없습니다.</p>'; return; } list.innerHTML = notices.map((notice) => `<article class="admin-notice"><h3>${escapeHtml(notice.title)}</h3>${notice.body ? `<p>${escapeHtml(notice.body)}</p>` : ""}<div class="notice-meta"><span>${courseNames[notice.course]} · ${new Date(notice.published_at).toLocaleDateString("ko-KR")} · ${notice.is_published ? "공개" : "비공개"}</span><span class="notice-actions"><button data-edit="${notice.id}">수정</button><button class="delete" data-delete="${notice.id}">삭제</button></span></div></article>`).join(""); }
function escapeHtml(value) { const div = document.createElement("div"); div.textContent = value || ""; return div.innerHTML; }
document.querySelector("#filter-course").addEventListener("change", loadNotices);
document.querySelector("#notice-form").addEventListener("submit", async (event) => { event.preventDefault(); formMessage.textContent = ""; const id = document.querySelector("#notice-id").value; const record = { course: document.querySelector("#course").value, title: document.querySelector("#title").value.trim(), body: document.querySelector("#body").value.trim(), is_published: document.querySelector("#published").checked, updated_at: new Date().toISOString() }; const { error } = id ? await client.from("notices").update(record).eq("id", id) : await client.from("notices").insert(record); if (error) { formMessage.textContent = "저장하지 못했습니다. 관리자 권한과 Supabase 설정을 확인해 주세요."; return; } resetForm(); loadNotices(); });
function resetForm() { document.querySelector("#notice-form").reset(); document.querySelector("#notice-id").value = ""; document.querySelector("#form-heading").textContent = "새 공지 작성"; document.querySelector("#cancel-edit").hidden = true; formMessage.textContent = ""; }
document.querySelector("#cancel-edit").addEventListener("click", resetForm);
document.querySelector("#admin-notice-list").addEventListener("click", async (event) => { const id = event.target.dataset.edit || event.target.dataset.delete; if (!id) return; const notice = notices.find((item) => item.id === id); if (event.target.dataset.edit) { document.querySelector("#notice-id").value = notice.id; document.querySelector("#course").value = notice.course; document.querySelector("#title").value = notice.title; document.querySelector("#body").value = notice.body || ""; document.querySelector("#published").checked = notice.is_published; document.querySelector("#form-heading").textContent = "공지 수정"; document.querySelector("#cancel-edit").hidden = false; window.scrollTo({ top: 0, behavior: "smooth" }); return; } if (!confirm("이 공지사항을 삭제할까요?")) return; const { error } = await client.from("notices").delete().eq("id", id); if (error) { alert("삭제하지 못했습니다."); return; } loadNotices(); });
updateView();
