const token = new URLSearchParams(location.search).get("token") || "";
let expiresAt = 0;
let requestedCode = "";
const message = document.querySelector("#message");
const codeInput = document.querySelector("#access-code");
async function request(action, payload) { const response = await fetch(`/api/attendance?action=${action}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "오류가 발생했습니다."); return data; }
async function openSession(code) { if (!token && code.length !== 6) return; try { const data = await request("session", token ? { token } : { access_code: code }); requestedCode = code; expiresAt = new Date(data.session.expires_at).getTime(); document.querySelector("#session-info").textContent = `${data.session.week}주차 · ${data.session.period}교시 출석`; document.querySelector("#timer-wrap").hidden = false; document.querySelector("#timer-bar").hidden = false; document.querySelector("#timer-guide").textContent = "시간이 끝나면 출석할 수 없습니다. 정보를 빠르게 확인해 제출하세요."; tick(); } catch (error) { message.textContent = error.message; } }
function tick() { const seconds = Math.max(0, Math.ceil((expiresAt - Date.now()) / 1000)); document.querySelector("#timer").textContent = String(seconds).padStart(2, "0"); document.querySelector("#timer-progress").style.width = `${Math.min(100, (seconds / 30) * 100)}%`; if (!seconds) { message.textContent = "출석 시간이 종료되었습니다."; document.querySelector("#checkin-form").querySelector("button").disabled = true; return; } setTimeout(tick, 250); }
codeInput.addEventListener("input", () => { const code = codeInput.value.trim(); if (code.length === 6 && code !== requestedCode) openSession(code); });
document.querySelector("#checkin-form").addEventListener("submit", async (event) => { event.preventDefault(); message.className = ""; try { const data = await request("checkin", { token, access_code: codeInput.value.trim(), student_id: document.querySelector("#student-id").value.trim(), name: document.querySelector("#student-name").value.trim(), phone: document.querySelector("#student-phone").value }); message.textContent = data.message; message.className = "success"; event.target.reset(); } catch (error) { message.textContent = error.message; } });
if (token) openSession("");
