const token = new URLSearchParams(location.search).get("token") || "";
const courseNames = { ai: "AI수처리", visualization: "경영정보시각화", excel: "비즈니스엑셀실무", accounting: "스타트업세무전산회계" };
let expiresAt = 0, requestedCode = "";
const message = document.querySelector("#message"), codeInput = document.querySelector("#access-code"), result = document.querySelector("#result");
async function request(action, payload) { const response = await fetch(`/api/attendance?action=${action}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const text = await response.text(); let data; try { data = text ? JSON.parse(text) : {}; } catch { throw new Error("출석 서버가 일시적으로 응답하지 않습니다. 잠시 후 다시 시도해 주세요."); } if (!response.ok) throw new Error(data.error || "오류가 발생했습니다."); return data; }
async function openSession(code) { if (!token && code.length !== 6) return; try { const data = await request("session", token ? { token } : { access_code: code }); requestedCode = code; expiresAt = new Date(data.session.expires_at).getTime(); const courseName = courseNames[data.session.course] || "강의"; document.querySelector("h1").textContent = `${courseName} 출석 체크`; document.title = `${courseName} 출석 체크 | HONG EON JOO`; document.querySelector("#session-info").textContent = `${data.session.week}주차 · ${data.session.period}교시 출석`; document.querySelector("#timer-wrap").hidden = false; document.querySelector("#timer-bar").hidden = false; document.querySelector("#timer-guide").textContent = "시간이 끝나면 출석할 수 없습니다. 정보를 빠르게 확인해 제출하세요."; tick(); } catch (error) { message.textContent = error.message; } }
function tick() { const seconds = Math.max(0, Math.ceil((expiresAt - Date.now()) / 1000)); document.querySelector("#timer").textContent = String(seconds).padStart(2, "0"); document.querySelector("#timer-progress").style.width = `${Math.min(100, seconds / 30 * 100)}%`; if (!seconds) { message.textContent = "출석 시간이 종료되었습니다."; document.querySelector("#checkin-form button").disabled = true; return; } setTimeout(tick, 250); }
function renderSummary(attendance) { const sheet = attendance.sessions.map((item) => `<th>${item.week}주 ${item.period}교시</th>`).join(""); const marks = attendance.sessions.map((item) => `<td class="${item.present ? "present" : "absent"}">${item.present ? "출석" : "/"}</td>`).join(""); const grades = attendance.grades.map((grade) => `<tr class="${grade.absences === attendance.absences ? "current" : ""}"><td>${grade.absences}</td><td>${grade.score}</td></tr>`).join(""); result.innerHTML = `<h2>출석 처리되었습니다.</h2><p class="result-score">현재까지 <b>${attendance.absences}회 결석</b> · 출석점수 <b>${attendance.score}</b> / 20점</p><div class="sheet"><table><thead><tr>${sheet}</tr></thead><tbody><tr>${marks}</tr></tbody></table></div><details class="grading" open><summary>출석성적 환산표 (${attendance.hoursPerWeek}시간 수업)</summary><table class="grade-table"><thead><tr><th>결석시수</th><th>출석점수</th></tr></thead><tbody>${grades}</tbody></table></details>`; result.hidden = false; }
codeInput.addEventListener("input", () => { const code = codeInput.value.trim(); if (code.length === 6 && code !== requestedCode) openSession(code); });
document.querySelector("#checkin-form").addEventListener("submit", async (event) => { event.preventDefault(); message.className = ""; result.hidden = true; try { const data = await request("checkin", { token, access_code: codeInput.value.trim(), student_id: document.querySelector("#student-id").value.trim(), name: document.querySelector("#student-name").value.trim(), phone: document.querySelector("#student-phone").value }); message.textContent = data.message; message.className = "success"; renderSummary(data.attendance); } catch (error) { message.textContent = error.message; } });
if (token) openSession("");
