const client = window.supabaseClient;
const courseNames = { ai: "AI수처리", visualization: "경영정보시각화", excel: "비즈니스엑셀", accounting: "스타트업세무전산회계" };
const coursePeriods = { ai: 2, visualization: 3, excel: 3, accounting: 3 };
let matrixData = null;
async function token() { const { data: { session } } = await client.auth.getSession(); return session?.access_token; }
async function api(action, body = {}) { const response = await fetch(`/api/attendance?action=${action}`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${await token()}` }, body: JSON.stringify({ action, origin: location.origin, ...body }) }); const text = await response.text(); let data; try { data = text ? JSON.parse(text) : {}; } catch { throw new Error("출석 서버가 일시적으로 응답하지 않습니다. 잠시 후 다시 시도해 주세요."); } if (!response.ok) throw new Error(data.error || "오류가 발생했습니다."); return data; }
function populatePeriods() { const course = document.querySelector("#start-course").value; document.querySelector("#start-period").innerHTML = Array.from({ length: coursePeriods[course] }, (_, i) => `<option value="${i + 1}">${i + 1}교시</option>`).join(""); }
document.querySelector("#start-week").innerHTML = Array.from({ length: 15 }, (_, i) => `<option value="${i + 1}">${i + 1}주차</option>`).join("");
document.querySelector("#start-course").addEventListener("change", populatePeriods); populatePeriods();
async function updateView() { const access = await token(); document.querySelector("#login-view").hidden = Boolean(access); document.querySelector("#attendance-view").hidden = !access; if (access) loadMatrix(); }
document.querySelector("#login-form").addEventListener("submit", async (event) => { event.preventDefault(); const { error } = await client.auth.signInWithPassword({ email: document.querySelector("#email").value, password: document.querySelector("#password").value }); document.querySelector("#login-message").textContent = error ? "로그인 정보를 확인해 주세요." : ""; if (!error) updateView(); });
document.querySelector("#logout").addEventListener("click", async () => { await client.auth.signOut(); updateView(); });
document.querySelectorAll(".tabs button").forEach((button) => button.addEventListener("click", () => { document.querySelectorAll(".tabs button,.panel").forEach((item) => item.classList.remove("active")); button.classList.add("active"); document.querySelector(`#${button.dataset.panel}`).classList.add("active"); if (button.dataset.panel === "matrix") loadMatrix(); }));
document.querySelector("#start-form").addEventListener("submit", async (event) => { event.preventDefault(); const message = document.querySelector("#start-message"); message.textContent = ""; try { const data = await api("start", { course: document.querySelector("#start-course").value, week: +document.querySelector("#start-week").value, period: +document.querySelector("#start-period").value, mode: document.querySelector("#start-mode").value }); const card = document.querySelector("#session-card"); card.innerHTML = `<h2>${courseNames[data.session.course]} · ${data.session.week}주차 ${data.session.period}교시</h2><p class="code">${data.session.access_code}</p><canvas class="qr" id="qr"></canvas><p><a class="session-link" href="${data.attendanceUrl}" target="_blank" rel="noopener">출석 페이지 열기 ↗</a></p><p class="hint">30초 동안만 유효합니다.</p>`; QRCode.toCanvas(document.querySelector("#qr"), data.attendanceUrl, { width: 250, margin: 1 }); } catch (error) { message.textContent = error.message; } });
function parseCsv(text) { return text.replace(/^\uFEFF/, "").trim().split(/\r?\n/).slice(1).map((line) => line.split(",").map((cell) => cell.trim())).filter((row) => row.length >= 3).map(([student_id, name, phone]) => ({ student_id, name, phone })); }
document.querySelector("#roster-form").addEventListener("submit", async (event) => { event.preventDefault(); const message = document.querySelector("#roster-message"); const file = document.querySelector("#roster-file").files[0]; if (!file) return; try { const students = parseCsv(await file.text()); const data = await api("import-roster", { course: document.querySelector("#roster-course").value, students }); message.textContent = `${data.imported}명의 수강생 명단을 저장했습니다.`; message.style.color = "#176234"; } catch (error) { message.textContent = error.message; message.style.color = "#a22"; } });
function label(session) { const date = new Date(session.starts_at).toLocaleDateString("ko-KR", { month: "numeric", day: "numeric" }); return `${date} / ${session.period}교시`; }
async function loadMatrix() { const message = document.querySelector("#matrix-message"); try { matrixData = await api("matrix", { course: document.querySelector("#matrix-course").value }); const head = `<tr><th>학번</th><th>이름</th><th>휴대폰</th>${matrixData.sessions.map((session) => `<th>${label(session)}</th>`).join("")}</tr>`; const rows = matrixData.rows.map((row) => `<tr><td>${row.student_id}</td><td>${row.name}</td><td>${row.phone}</td>${row.marks.map((mark) => `<td>${mark}</td>`).join("")}</tr>`).join(""); document.querySelector("#matrix-table").innerHTML = head + rows; message.textContent = matrixData.rows.length ? "" : "등록된 수강생 명단이 없습니다."; } catch (error) { message.textContent = error.message; } }
document.querySelector("#matrix-course").addEventListener("change", loadMatrix);
document.querySelector("#download").addEventListener("click", () => { if (!matrixData) return; const headings = ["학번", "이름", "휴대폰", ...matrixData.sessions.map(label)]; const lines = [headings, ...matrixData.rows.map((row) => [row.student_id, row.name, row.phone, ...row.marks])].map((line) => line.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(",")); const blob = new Blob(["\uFEFF" + lines.join("\r\n")], { type: "text/csv;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `${courseNames[document.querySelector("#matrix-course").value]}_출석현황.csv`; link.click(); URL.revokeObjectURL(link.href); });
updateView();
