const COURSES = { ai: { name: "AI수처리", periods: 2 }, visualization: { name: "경영정보시각화", periods: 3 }, excel: { name: "비즈니스엑셀", periods: 3 }, accounting: { name: "스타트업세무전산회계", periods: 3 } };
const DEFAULT_PC_RANGES = [["211.253.246.211", "211.253.246.250"], ["211.253.246.61", "211.253.246.110"], ["211.252.61.251", "211.252.61.251"]];
function json(response, status = 200) { return { statusCode: status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" }, body: JSON.stringify(response) }; }
function getBody(event) { try { return JSON.parse(event.body || "{}"); } catch { return {}; } }
function cleanPhone(value) { return String(value || "").replace(/\D/g, ""); }
function clientIp(event) { return String(event.headers["x-forwarded-for"] || event.headers["x-vercel-forwarded-for"] || "").split(",")[0].trim(); }
function ipNumber(ip) { const parts = ip.split("."); return parts.length === 4 && parts.every((part) => /^\d+$/.test(part) && +part < 256) ? parts.reduce((total, part) => total * 256 + +part, 0) : null; }
function parseRanges(value, fallback = []) { try { const parsed = JSON.parse(value || ""); return Array.isArray(parsed) ? parsed : fallback; } catch { return fallback; } }
function ipInRanges(ip, ranges) { const value = ipNumber(ip); return value !== null && ranges.some(([start, end]) => value >= ipNumber(start) && value <= ipNumber(end)); }
function config() { return { url: process.env.SUPABASE_URL, serviceKey: process.env.SUPABASE_SERVICE_ROLE_KEY, adminEmail: process.env.ADMIN_EMAIL || "digital@ktc.ac.kr", pcRanges: [...DEFAULT_PC_RANGES, ...parseRanges(process.env.ALLOWED_PC_RANGES)], wirelessRanges: parseRanges(process.env.ALLOWED_WIRELESS_RANGES) }; }
async function sb(path, options = {}) { const c = config(); const response = await fetch(`${c.url}/rest/v1/${path}`, { ...options, headers: { apikey: c.serviceKey, Authorization: `Bearer ${c.serviceKey}`, "Content-Type": "application/json", Prefer: options.prefer || "return=representation", ...(options.headers || {}) } }); const text = await response.text(); let data; try { data = text ? JSON.parse(text) : null; } catch { data = text; } if (!response.ok) throw new Error(data?.message || data?.hint || "Database request failed"); return data; }
async function admin(event) { const token = String(event.headers.authorization || "").replace(/^Bearer\s+/i, ""); const c = config(); if (!token || !c.url || !c.serviceKey) return false; const response = await fetch(`${c.url}/auth/v1/user`, { headers: { apikey: c.serviceKey, Authorization: `Bearer ${token}` } }); if (!response.ok) return false; const user = await response.json(); return user.email?.toLowerCase() === c.adminEmail.toLowerCase(); }
function sessionOpen(session, event) { const now = Date.now(); if (!session || !session.active || now > new Date(session.expires_at).getTime()) return [false, "출석 시간이 종료되었습니다."]; const c = config(); const ranges = session.mode === "wireless" ? c.wirelessRanges : c.pcRanges; if (!ipInRanges(clientIp(event), ranges)) return [false, "허용된 교내망에서만 출석할 수 있습니다."]; return [true]; }
function filter(value) { return encodeURIComponent(String(value)); }
async function startSession(event, body) { if (!(await admin(event))) return json({ error: "관리자 인증이 필요합니다." }, 401); const course = COURSES[body.course], week = Number(body.week), period = Number(body.period), mode = body.mode === "wireless" ? "wireless" : "pc"; if (!course || !Number.isInteger(week) || week < 1 || week > 15 || !Number.isInteger(period) || period < 1 || period > course.periods) return json({ error: "과목·주차·교시를 확인해 주세요." }, 400); if (mode === "wireless" && !config().wirelessRanges.length) return json({ error: "무선망 공인 IP가 아직 등록되지 않았습니다." }, 400); const now = new Date(); const record = { course: body.course, week, period, mode, token: crypto.randomUUID(), access_code: String(Math.floor(100000 + Math.random() * 900000)), active: true, starts_at: now.toISOString(), expires_at: new Date(now.getTime() + 30000).toISOString() }; const [saved] = await sb("attendance_sessions", { method: "POST", body: JSON.stringify(record) }); return json({ session: saved, attendanceUrl: `${body.origin || ""}/attendance.html?token=${saved.token}` }); }
async function importRoster(event, body) { if (!(await admin(event))) return json({ error: "관리자 인증이 필요합니다." }, 401); if (!COURSES[body.course] || !Array.isArray(body.students)) return json({ error: "명단 형식을 확인해 주세요." }, 400); const rows = body.students.map((student) => ({ course: body.course, student_id: String(student.student_id || "").trim(), name: String(student.name || "").trim(), phone: cleanPhone(student.phone) })).filter((student) => /^\d{9}$/.test(student.student_id) && student.name && /^01\d{8,9}$/.test(student.phone)); if (!rows.length) return json({ error: "유효한 학생 정보가 없습니다." }, 400); await sb("course_roster?on_conflict=course,student_id", { method: "POST", prefer: "resolution=merge-duplicates,return=minimal", body: JSON.stringify(rows) }); return json({ imported: rows.length }); }
async function matrix(event, course) { if (!(await admin(event))) return json({ error: "관리자 인증이 필요합니다." }, 401); const [roster, sessions, records] = await Promise.all([sb(`course_roster?course=eq.${filter(course)}&select=student_id,name,phone&order=student_id.asc`), sb(`attendance_sessions?course=eq.${filter(course)}&select=id,week,period,starts_at,expires_at&order=starts_at.asc`), sb(`attendance_records?course=eq.${filter(course)}&select=student_id,session_id,checked_at`)]); const checked = new Set(records.map((record) => `${record.student_id}:${record.session_id}`)); return json({ roster, sessions, rows: roster.map((student) => ({ ...student, marks: sessions.map((session) => checked.has(`${student.student_id}:${session.id}`) ? "" : "/") })) }); }
async function sessionForStudent(event, body) { const token = String(body.token || ""), code = String(body.access_code || ""), query = token ? `token=eq.${filter(token)}` : `access_code=eq.${filter(code)}`; const sessions = await sb(`attendance_sessions?${query}&select=id,course,week,period,mode,active,expires_at,access_code`); const session = sessions[0]; const [allowed, message] = sessionOpen(session, event); if (!allowed) return json({ error: message }, 403); return json({ session: { course: session.course, week: session.week, period: session.period, expires_at: session.expires_at } }); }
async function checkin(event, body) { const code = String(body.access_code || "").trim(); if (!/^\d{6}$/.test(code)) return json({ error: "6자리 출석 코드를 입력해 주세요." }, 400); const sessions = await sb(`attendance_sessions?${body.token ? `token=eq.${filter(body.token)}` : `access_code=eq.${filter(code)}`}&select=*`); const session = sessions[0]; if (!session || session.access_code !== code) return json({ error: "출석 코드가 일치하지 않습니다." }, 403); const [allowed, message] = sessionOpen(session, event); if (!allowed) return json({ error: message }, 403); const studentId = String(body.student_id || "").trim(), name = String(body.name || "").trim(), phone = cleanPhone(body.phone); if (!/^\d{9}$/.test(studentId) || !name || !/^01\d{8,9}$/.test(phone)) return json({ error: "학번 9자리, 이름, 휴대폰번호를 확인해 주세요." }, 400); const roster = await sb(`course_roster?course=eq.${filter(session.course)}&student_id=eq.${filter(studentId)}&select=*`); if (!roster[0] || roster[0].name !== name || roster[0].phone !== phone) return json({ error: "수강생 명단의 정보와 일치하지 않습니다." }, 403); try { await sb("attendance_records", { method: "POST", body: JSON.stringify({ session_id: session.id, course: session.course, student_id: studentId, name, phone, client_ip: clientIp(event) }) }); } catch (error) { if (String(error.message).includes("duplicate")) return json({ error: "이미 이 교시에 출석 처리되었습니다." }, 409); throw error; } return json({ ok: true, message: "출석 처리되었습니다." }); }
async function route(event) { try { const action = event.queryStringParameters?.action || getBody(event).action, body = getBody(event); if (action === "start") return startSession(event, body); if (action === "import-roster") return importRoster(event, body); if (action === "matrix") return matrix(event, body.course || event.queryStringParameters?.course); if (action === "session") return sessionForStudent(event, body); if (action === "checkin") return checkin(event, body); return json({ error: "Unknown action" }, 404); } catch (error) { return json({ error: error.message || "출석 시스템 오류가 발생했습니다." }, 500); } }
export default async function handler(req, res) { const result = await route({ headers: req.headers, body: typeof req.body === "string" ? req.body : JSON.stringify(req.body || {}), queryStringParameters: req.query || {} }); for (const [key, value] of Object.entries(result.headers || {})) res.setHeader(key, value); return res.status(result.statusCode).send(result.body); }
