function json(body,status=200){return{statusCode:status,headers:{"Content-Type":"application/json","Cache-Control":"no-store"},body:JSON.stringify(body)}}
function read(event){try{return JSON.parse(event.body||"{}")}catch{return{}}}
function config(){return{url:process.env.SUPABASE_URL,key:process.env.SUPABASE_SERVICE_ROLE_KEY,admin:process.env.ADMIN_EMAIL||"digital@ktc.ac.kr"}}
function esc(value){return encodeURIComponent(String(value))}
async function sb(path,options={}){const c=config();if(!c.url||!c.key)throw new Error("설문 서버 설정이 필요합니다.");const r=await fetch(`${c.url}/rest/v1/${path}`,{...options,headers:{apikey:c.key,Authorization:`Bearer ${c.key}`,"Content-Type":"application/json",Prefer:options.prefer||"return=representation",...(options.headers||{})}}),text=await r.text();let data;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.message||"데이터 요청에 실패했습니다.");return data}
async function admin(event){const token=String(event.headers.authorization||"").replace(/^Bearer\s+/i,""),c=config();if(!token)return false;const r=await fetch(`${c.url}/auth/v1/user`,{headers:{apikey:c.key,Authorization:`Bearer ${token}`}});return r.ok&&(await r.json()).email?.toLowerCase()===c.admin.toLowerCase()}
async function create(event,d){if(!await admin(event))return json({error:"관리자 인증이 필요합니다."},401);const question=String(d.question||"").trim(),type=d.poll_type==="word"?"word":"choice",options=Array.isArray(d.options)?d.options.map(x=>String(x).trim()).filter(Boolean).slice(0,6):[];if(!question)return json({error:"질문을 입력해 주세요."},400);if(type==="choice"&&options.length<2)return json({error:"선택지는 두 개 이상 필요합니다."},400);const row={access_code:String(Math.floor(100000+Math.random()*900000)),question,poll_type:type,options,active:true};const[saved]=await sb("live_polls",{method:"POST",body:JSON.stringify(row)});return json({poll:saved,url:`${d.origin||""}/poll.html?code=${saved.access_code}`})}
async function find(code){const[record]=await sb(`live_polls?access_code=eq.${esc(code)}&select=id,access_code,question,poll_type,options,active`);return record}
async function get(event,d){const poll=await find(d.access_code);return poll&&poll.active?json({poll}):json({error:"진행 중인 설문을 찾을 수 없습니다."},404)}
async function vote(event,d){const poll=await find(d.access_code),answer=String(d.response||"").trim(),key=String(d.participant_key||"");if(!poll||!poll.active)return json({error:"설문이 종료되었거나 존재하지 않습니다."},403);if(!key||!answer)return json({error:"응답을 입력해 주세요."},400);if(poll.poll_type==="choice"&&!poll.options.includes(answer))return json({error:"선택지를 확인해 주세요."},400);try{await sb("live_poll_responses",{method:"POST",body:JSON.stringify({poll_id:poll.id,response:answer,participant_key:key})})}catch(error){if(String(error.message).includes("duplicate"))return json({error:"이 설문에는 이미 응답했습니다."},409);throw error}return json({ok:true})}
async function results(event,d){if(!await admin(event))return json({error:"관리자 인증이 필요합니다."},401);const poll=await find(d.access_code);if(!poll)return json({error:"설문을 찾을 수 없습니다."},404);const responses=await sb(`live_poll_responses?poll_id=eq.${poll.id}&select=response,created_at`);return json({poll,responses})}
async function close(event,d){if(!await admin(event))return json({error:"관리자 인증이 필요합니다."},401);const poll=await find(d.access_code);if(!poll)return json({error:"설문을 찾을 수 없습니다."},404);await sb(`live_polls?id=eq.${poll.id}`,{method:"PATCH",body:JSON.stringify({active:false,closed_at:new Date().toISOString()})});return json({ok:true})}
async function list(event){if(!await admin(event))return json({error:"관리자 인증이 필요합니다."},401);const polls=await sb("live_polls?select=id,access_code,question,poll_type,active,created_at&order=created_at.desc");const counts=await sb("live_poll_responses?select=poll_id");return json({polls:polls.map(p=>({...p,responses:counts.filter(x=>x.poll_id===p.id).length}))})}
async function remove(event,d){if(!await admin(event))return json({error:"관리자 인증이 필요합니다."},401);await sb(`live_polls?id=eq.${esc(d.id)}`,{method:"DELETE",prefer:"return=minimal"});return json({ok:true})}
async function route(event){try{const d=read(event),action=event.queryStringParameters?.action||d.action;if(action==="create")return await create(event,d);if(action==="get")return await get(event,d);if(action==="vote")return await vote(event,d);if(action==="results")return await results(event,d);if(action==="close")return await close(event,d);if(action==="list")return await list(event);if(action==="delete")return await remove(event,d);return json({error:"Unknown action"},404)}catch(error){return json({error:error.message||"설문 시스템 오류"},500)}}
export default async function handler(req,res){const result=await route({headers:req.headers,body:typeof req.body==="string"?req.body:JSON.stringify(req.body||{}),queryStringParameters:req.query||{}});for(const[k,v]of Object.entries(result.headers))res.setHeader(k,v);return res.status(result.statusCode).send(result.body)}
